var result = 10;
try {
    console.log(reslt);
} catch(error) {
    console.log("An error has occured", error.message);
}